### ISSUE TITLE
dataCopiedToCluster file missing

### ISSUE THREAD

**Issue by Gerbenvandervries** [molgenis/NGS_Automated#15]
copyRawDataToPrm.sh: line 96  '.dataCopiedToCluster' should probable be 'dataCopiedToDiagnosticsCluster'

**Comment by RoanKanninga** [comment]
I think you are right, I can see that this is changed (in the history of the file) when we tried to make a automated connection with calculon.

**Comment by RoanKanninga** [comment]
#fixed in f3eaaaba36d7fba908e44d1b92aff2dc455f0c62
